version: '3.0'

services:
  uploader:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
  builder:
    build: ./builder
    env_file:
      - ./builder/.env
    depends_on:
      - redis
  redis:
    image: redis:latest